const countries = [
  { name: "USA", img: "path_to_image" },
  { name: "Russia", img: "path_to_image" },
  { name: "China", img: "path_to_image" },
  { name: "India", img: "path_to_image" },
  { name: "EU", img: "path_to_image" },
  { name: "Japan", img: "path_to_image" },
  { name: "S. Korea", img: "path_to_image" },
  { name: "Canada", img: "path_to_image" },
  { name: "Brazil", img: "path_to_image" },
  { name: "Indonesia", img: "path_to_image" },
  { name: "Mexico", img: "path_to_image" },
  { name: "UK", img: "path_to_image" },
  { name: "France", img: "path_to_image" },
  { name: "Australia", img: "path_to_image" },
  { name: "Turkey", img: "path_to_image" },
  { name: "Pakistan", img: "path_to_image" },
  { name: "Nigeria", img: "path_to_image" },
  { name: "UAE", img: "path_to_image" },
  { name: "Vietnam", img: "path_to_image" },
  { name: "Thailand", img: "path_to_image" },
  { name: "Philippines", img: "path_to_image" },
  { name: "Argentina", img: "path_to_image" },
  { name: "S. Africa", img: "path_to_image" },
  { name: "Ethiopia", img: "path_to_image" },
  { name: "Poland", img: "path_to_image" },
  { name: "Romania", img: "path_to_image" },
  { name: "Israel", img: "path_to_image" },
  { name: "Sweden", img: "path_to_image" },
  { name: "Finland", img: "path_to_image" },
  { name: "Norway", img: "path_to_image" },
  { name: "Denmark", img: "path_to_image" },
  { name: "Switzerland", img: "path_to_image" },
  { name: "Hungary", img: "path_to_image" },
  { name: "Czech Rep.", img: "path_to_image" },
  { name: "Croatia", img: "path_to_image" },
  { name: "Slovenia", img: "path_to_image" },
  { name: "Serbia", img: "path_to_image" },
  { name: "Bosnia", img: "path_to_image" },
  { name: "Albania", img: "path_to_image" },
  { name: "Kosovo", img: "path_to_image" },
  { name: "Georgia", img: "path_to_image" },
  { name: "Armenia", img: "path_to_image" },
  { name: "Azerbaijan", img: "path_to_image" },
  { name: "Moldova", img: "path_to_image" },
  { name: "Belarus", img: "path_to_image" },
  { name: "Uzbekistan", img: "path_to_image" },
  { name: "Kyrgyzstan", img: "path_to_image" },
  { name: "Turkmenistan", img: "path_to_image" },
  { name: "Tajikistan", img: "path_to_image" },
  { name: "Sri Lanka", img: "path_to_image" },
  { name: "Nepal", img: "path_to_image" },
  { name: "Bangladesh", img: "path_to_image" },
  { name: "Myanmar", img: "path_to_image" },
  { name: "Jordan", img: "path_to_image" },
  { name: "Kuwait", img: "path_to_image" },
  { name: "Qatar", img: "path_to_image" },
  { name: "Bahrain", img: "path_to_image" },
  { name: "Oman", img: "path_to_image" },
  { name: "Lebanon", img: "path_to_image" },
  { name: "Iraq", img: "path_to_image" },
  { name: "Yemen", img: "path_to_image" },
  { name: "Libya", img: "path_to_image" },
  { name: "Sudan", img: "path_to_image" },
  { name: "Somalia", img: "path_to_image" },
  { name: "Chad", img: "path_to_image" },
  { name: "CAR", img: "path_to_image" },
  { name: "Cameroon", img: "path_to_image" },
  { name: "Gabon", img: "path_to_image" },
  { name: "Congo", img: "path_to_image" },
  { name: "Seychelles", img: "path_to_image" },
  { name: "Mauritius", img: "path_to_image" },
  { name: "Madagascar", img: "path_to_image" },
  { name: "Mozambique", img: "path_to_image" },
  { name: "Angola", img: "path_to_image" },
  { name: "Zambia", img: "path_to_image" },
  { name: "Burundi", img: "path_to_image" },
  { name: "Rwanda", img: "path_to_image" },
  { name: "Botswana", img: "path_to_image" },
  { name: "Namibia", img: "path_to_image" },
  { name: "Malawi", img: "path_to_image" },
  { name: "Liberia", img: "path_to_image" },
  { name: "Sierra Leone", img: "path_to_image" },
  { name: "Burkina Faso", img: "path_to_image" },
  { name: "Mali", img: "path_to_image" },
  { name: "Ghana", img: "path_to_image" },
  { name: "Ivory Coast", img: "path_to_image" },
  { name: "Togo", img: "path_to_image" },
  { name: "Benin", img: "path_to_image" },
  { name: "Niger", img: "path_to_image" },
  { name: "Mauritania", img: "path_to_image" },
  { name: "Eswatini", img: "path_to_image" },
  { name: "Lesotho", img: "path_to_image" },
  { name: "Guinea", img: "path_to_image" },
  { name: "Guinea-Bissau", img: "path_to_image" },
  { name: "Comoros", img: "path_to_image" },
  { name: "Cape Verde", img: "path_to_image" },
  { name: "São Tomé", img: "path_to_image" },
  { name: "Timor-Leste", img: "path_to_image" },
  { name: "Solomon Is.", img: "path_to_image" },
  { name: "Vanuatu", img: "path_to_image" },
  { name: "Fiji", img: "path_to_image" },
  { name: "Tonga", img: "path_to_image" },
  { name: "Samoa", img: "path_to_image" },
  { name: "Palau", img: "path_to_image" },
  { name: "Micronesia", img: "path_to_image" },
  { name: "Marshall Is.", img: "path_to_image" },
  { name: "Nauru", img: "path_to_image" },
  { name: "Kiribati", img: "path_to_image" },
  { name: "Tuvalu", img: "path_to_image" },
  { name: "Nicaragua", img: "path_to_image" },
  { name: "Honduras", img: "path_to_image" },
  { name: "El Salvador", img: "path_to_image" },
  { name: "Costa Rica", img: "path_to_image" },
  { name: "Panama", img: "path_to_image" },
  { name: "Guatemala", img: "path_to_image" },
  { name: "Belize", img: "path_to_image" },
  { name: "Saint Lucia", img: "path_to_image" },
  { name: "Saint Vincent", img: "path_to_image" },
  { name: "Barbados", img: "path_to_image" },
  { name: "Grenada", img: "path_to_image" },
  { name: "Trinidad", img: "path_to_image" },
  { name: "Jamaica", img: "path_to_image" },
  { name: "Dominica", img: "path_to_image" },
  { name: "St. Kitts", img: "path_to_image" },
  { name: "Antigua", img: "path_to_image" },
  { name: "Saint Pierre", img: "path_to_image" },
  { name: "Bermuda", img: "path_to_image" },
  { name: "Cayman Is.", img: "path_to_image" },
  { name: "BVI", img: "path_to_image" },
  { name: "Anguilla", img: "path_to_image" },
  { name: "Montserrat", img: "path_to_image" },
  { name: "Turks & Caicos", img: "path_to_image" },
  { name: "Saint Barthelemy", img: "path_to_image" },
  { name: "Saint Martin", img: "path_to_image" },
  { name: "Guadeloupe", img: "path_to_image" },
  { name: "Martinique", img: "path_to_image" },
  { name: "French Guyana", img: "path_to_image" },
  { name: "Reunion", img: "path_to_image" },
  { name: "Mayotte", img: "path_to_image" },
  { name: "New Caledonia", img: "path_to_image" },
  { name: "Polynesia", img: "path_to_image" },
  { name: "Wallis & Futuna", img: "path_to_image" },
  { name: "Cook Is.", img: "path_to_image" },
  { name: "Niue", img: "path_to_image" },
  { name: "A. Samoa", img: "path_to_image" },
  { name: "Guam", img: "path_to_image" },
  { name: "N. Mariana Is.", img: "path_to_image" },
  { name: "Federated States", img: "path_to_image" },
  { name: "Palau", img: "path_to_image" },
  { name: "Micronesia", img: "path_to_image" },
  { name: "Nauru", img: "path_to_image" }
];
