name: Run Instagram Bot

on:
  workflow_dispatch:  # Memungkinkan manual trigger
  schedule:
    - cron: "0 * * * *"  # Menjalankan setiap jam pada menit ke-0

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2  # Ambil kode dari repositori menggunakan versi v4.2.2
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Bot
      run: python instagram_bot.py
      env:
        IG_USERNAME: "mrobotfx"  # Masukkan username Instagram Anda langsung di sini
        IG_PASSWORD: "$123456789$"  # Masukkan kata sandi Instagram Anda langsung di sini
